name: release

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build obs.min.js
        run: npm run build

      - name: SHA256 checksum
        run: shasum -a 256 obs.min.js > SHA256SUMS.txt

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: 'Obs.js ${{ github.ref_name }}'
          generate_release_notes: true
          files: |
            obs.min.js
            SHA256SUMS.txt

